---
ID: "60fb9a70-129b-463b-affd-fe29eadab280"
Parent: "f66945aa-2e04-44e0-9460-b78a18fa5f53"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/NimbleSearch UI/Parameters/ParametersTemplate_SearchBoxConfigurations/Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170714T193030Z
