---
ID: "92eccd30-9edc-4218-83d5-5aecf47428e7"
Parent: "299dfffc-e615-404c-93b5-da6c8c872037"
Template: "299dfffc-e615-404c-93b5-da6c8c872037"
Path: /sitecore/templates/Foundation/NimbleSearch UI/Parameters/ParametersTemplate_Configurations/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171113T195629Z
