---
ID: "d7a19c35-6320-462f-806f-0558feb6b214"
Parent: "299dfffc-e615-404c-93b5-da6c8c872037"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/NimbleSearch UI/Parameters/ParametersTemplate_Configurations/Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170714T193030Z
